/**
 * What the in-world self-test expects to find, generated from src/packs.
 *
 * These were read out of src/packs when the packs were built, and are
 * maintained here now. Every figure
 * here is the book's, by way of the import — a test that checks the system
 * against numbers somebody typed proves only that they can add up.
 */

export const EXPECTED = {
  "packs": {
    "species": 19,
    "classes": 52,
    "occupations": 33,
    "talents": 52,
    "feats": 138,
    "spells": 175,
    "psionics": 88,
    "weapons": 180,
    "armor": 40,
    "gear": 289,
    "creatures": 300,
    "vehicles": 85,
    "objects": 14,
    "rules": 53,
    "fx": 147,
    "tables": 26,
    "pregens": 6,
    "guide": 1,
    "scenes": 1
  },
  "species": {
    "uuid": "Compendium.modern20.species.Item.CFiLQnJ643KnHL8I",
    "name": "Ogre",
    "size": "large",
    "baseSpeed": 30,
    "reach": 10,
    "naturalArmor": 5,
    "attackBonus": 3,
    "extraHitDice": 4,
    "levelAdjustment": 3,
    "abilityModifiers": {"str": 10, "dex": -2, "con": 4, "int": -4, "wis": 0, "cha": -4},
    "traits": 2,
    "nonhuman": true
  },
  "class": {
    "uuid": "Compendium.modern20.classes.Item.HT4H6K30vjBuhX1b",
    "name": "Strong Hero",
    "levels": 3,
    "keyAbility": "str",
    "row": {
      "baseAttack": 3,
      "fort": 2,
      "ref": 1,
      "will": 1,
      "defense": 2,
      "reputation": 0
    }
  },
  "creatures": [
    {
      "uuid": "Compendium.modern20.creatures.Actor.u7J8wKrCSLBwBEua",
      "name": "Advanced Megalodon",
      "size": "colossal",
      "defense": 21,
      "squares": 6.0,
      "art": "systems/modern20/assets/tokens/lorc/wolf-head.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.LEQChrxP0XHypfnC",
      "name": "Advanced Acid Rainer",
      "size": "gargantuan",
      "defense": 12,
      "squares": 4.0,
      "art": "systems/modern20/assets/tokens/sbed/fire.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.Ok4xp65tFRGpw4Ur",
      "name": "Abominable Snowman (Advanced Yeti)",
      "size": "huge",
      "defense": 15,
      "squares": 3.0,
      "art": "systems/modern20/assets/tokens/lorc/horned-helm.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.v9pkbFbj88spXx7z",
      "name": "4th-level Vivilor",
      "size": "large",
      "defense": 18,
      "squares": 2.0,
      "art": "systems/modern20/assets/tokens/lorc/daemon-skull.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.yCwq6awhmtGSez5S",
      "name": "2nd-level Vivilor",
      "size": "medium",
      "defense": 14,
      "squares": 1.0,
      "art": "systems/modern20/assets/tokens/lorc/daemon-skull.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.L9jZrePjtic15rBU",
      "name": "1st-level Vivilor",
      "size": "small",
      "defense": 13,
      "squares": 1.0,
      "art": "systems/modern20/assets/tokens/lorc/daemon-skull.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.9pWX6exYM9fi2PTh",
      "name": "Advanced Fire Wisp",
      "size": "tiny",
      "defense": 15,
      "squares": 0.5,
      "art": "systems/modern20/assets/tokens/sbed/fire.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.49Zw6EecxKMLJTo0",
      "name": "Bat",
      "size": "diminutive",
      "defense": 16,
      "squares": 0.5,
      "art": "systems/modern20/assets/tokens/lorc/wolf-head.svg"
    },
    {
      "uuid": "Compendium.modern20.creatures.Actor.TDhpmcxzdraodOke",
      "name": "Infester (grub)",
      "size": "fine",
      "defense": 24,
      "squares": 0.5,
      "art": "systems/modern20/assets/tokens/skoll/long-legged-spider.svg"
    }
  ],
  "weapon": {
    "uuid": "Compendium.modern20.weapons.Item.oRXjLtbZS4LDaa3c",
    "name": "Colt Python 1 (.357 revolver)",
    "damage": "2d6",
    "critical": "20",
    "rulesPage": "Compendium.modern20.rules.JournalEntry.KEk4tUapzxsIoENq.JournalEntryPage.RT8WnlwIoZ3cAS9K"
  },
  "pregens": [
    {
      "uuid": "Compendium.modern20.pregens.Actor.mJmV0LKqyj4LLOQk",
      "name": "Nate Okoye",
      "hp": 5,
      "wealth": 7,
      "items": 10,
      "className": "Charismatic Hero",
      "level": 1,
      "row": {
        "baseAttack": 0,
        "fort": 1,
        "ref": 1,
        "will": 0,
        "defense": 0,
        "reputation": 2
      },
      "classSkill": "bluff"
    },
    {
      "uuid": "Compendium.modern20.pregens.Actor.FWRnjpzxqrFGJkok",
      "name": "Ruth Ayers",
      "hp": 7,
      "wealth": 9,
      "items": 11,
      "className": "Dedicated Hero",
      "level": 1,
      "row": {
        "baseAttack": 0,
        "fort": 1,
        "ref": 0,
        "will": 1,
        "defense": 1,
        "reputation": 1
      },
      "classSkill": "treatInjury"
    },
    {
      "uuid": "Compendium.modern20.pregens.Actor.yBTgNU08MadQzagi",
      "name": "Teo Vance",
      "hp": 9,
      "wealth": 6,
      "items": 11,
      "className": "Fast Hero",
      "level": 1,
      "row": {
        "baseAttack": 0,
        "fort": 0,
        "ref": 1,
        "will": 0,
        "defense": 3,
        "reputation": 0
      },
      "classSkill": "drive"
    },
    {
      "uuid": "Compendium.modern20.pregens.Actor.xKuZQ0Z922ePfTlC",
      "name": "Dr. Ilse Brandt",
      "hp": 6,
      "wealth": 8,
      "items": 12,
      "className": "Smart Hero",
      "level": 1,
      "row": {
        "baseAttack": 0,
        "fort": 0,
        "ref": 0,
        "will": 1,
        "defense": 0,
        "reputation": 1
      },
      "classSkill": "computerUse"
    },
    {
      "uuid": "Compendium.modern20.pregens.Actor.I9qR0hCcns6EdgEm",
      "name": "Sergeant Dana Kessler",
      "hp": 10,
      "wealth": 6,
      "items": 12,
      "className": "Strong Hero",
      "level": 1,
      "row": {
        "baseAttack": 1,
        "fort": 1,
        "ref": 0,
        "will": 0,
        "defense": 1,
        "reputation": 0
      },
      "classSkill": "climb"
    },
    {
      "uuid": "Compendium.modern20.pregens.Actor.6xkcsadPkPnd4ozI",
      "name": "Marisol Okonkwo",
      "hp": 12,
      "wealth": 7,
      "items": 11,
      "className": "Tough Hero",
      "level": 1,
      "row": {
        "baseAttack": 0,
        "fort": 1,
        "ref": 0,
        "will": 0,
        "defense": 1,
        "reputation": 0
      },
      "classSkill": "climb"
    }
  ],
  "rulesPages": [
    {
      "pack": "armor",
      "name": "Banded mail",
      "uuid": "Compendium.modern20.rules.JournalEntry.cC6yOEvgjiSs8AyG.JournalEntryPage.vx2MEjc3pHfwQAuW"
    },
    {
      "pack": "classes",
      "name": "Acolyte",
      "uuid": "Compendium.modern20.rules.JournalEntry.hXGxrY1r1Ec6LQTW.JournalEntryPage.0JTk2bITfe4B02u6"
    },
    {
      "pack": "creatures",
      "name": "1st-level Vivilor",
      "uuid": "Compendium.modern20.rules.JournalEntry.F9sDg5FHLKUqVnLh.JournalEntryPage.YAky2fejdujfF06k"
    },
    {
      "pack": "feats",
      "name": "Acrobatic",
      "uuid": "Compendium.modern20.rules.JournalEntry.d6dDbFeCTSrHL6vJ.JournalEntryPage.WNAXtvgtyiic73kt"
    },
    {
      "pack": "fx",
      "name": "Ablative Paint Job",
      "uuid": "Compendium.modern20.rules.JournalEntry.PGmH1EOulpH0Dyl9.JournalEntryPage.XdzTqx60AejfD0rJ"
    },
    {
      "pack": "gear",
      "name": "10-gauge buckshot (10)",
      "uuid": "Compendium.modern20.rules.JournalEntry.KEk4tUapzxsIoENq.JournalEntryPage.aO8Ap7cKMDUUFrvK"
    },
    {
      "pack": "objects",
      "name": "Chain",
      "uuid": "Compendium.modern20.rules.JournalEntry.BW08qOlRSlaENtxF.JournalEntryPage.ZVIRSi83JXUEeVf3"
    },
    {
      "pack": "occupations",
      "name": "Academic",
      "uuid": "Compendium.modern20.rules.JournalEntry.J95B9XhYH6v4Joca.JournalEntryPage.TGMP5Gq4WL0DaGmO"
    },
    {
      "pack": "psionics",
      "name": "Attraction",
      "uuid": "Compendium.modern20.rules.JournalEntry.hXGxrY1r1Ec6LQTW.JournalEntryPage.nQGhA7HypQaoDD74"
    },
    {
      "pack": "spells",
      "name": "Aid",
      "uuid": "Compendium.modern20.rules.JournalEntry.hXGxrY1r1Ec6LQTW.JournalEntryPage.SPPE7CSFqeIHdIEd"
    },
    {
      "pack": "talents",
      "name": "Captivate",
      "uuid": "Compendium.modern20.rules.JournalEntry.ygo3sPzJhXS28OXD.JournalEntryPage.EWU8hHojcW05rWLl"
    },
    {
      "pack": "vehicles",
      "name": "1967 Chevrolet Camaro (sports coupe)",
      "uuid": "Compendium.modern20.rules.JournalEntry.cC6yOEvgjiSs8AyG.JournalEntryPage.shnZOpBvMs2FQ5O2"
    },
    {
      "pack": "weapons",
      "name": "40mm fragmentation grenade",
      "uuid": "Compendium.modern20.rules.JournalEntry.KEk4tUapzxsIoENq.JournalEntryPage.5wYhXtWqLt6aLUZ8"
    }
  ],
  "images": [
    "systems/modern20/assets/icons/andymeneely/police-badge.svg",
    "systems/modern20/assets/icons/carl-olsen/crossbow.svg",
    "systems/modern20/assets/icons/carl-olsen/flame.svg",
    "systems/modern20/assets/icons/delapouite/all-seeing-eye.svg",
    "systems/modern20/assets/icons/delapouite/american-shield.svg",
    "systems/modern20/assets/icons/delapouite/astronaut-helmet.svg",
    "systems/modern20/assets/icons/delapouite/backpack.svg",
    "systems/modern20/assets/icons/delapouite/binoculars.svg",
    "systems/modern20/assets/icons/delapouite/brass-knuckles.svg",
    "systems/modern20/assets/icons/delapouite/brick-wall.svg",
    "systems/modern20/assets/icons/delapouite/briefcase.svg",
    "systems/modern20/assets/icons/delapouite/bus.svg",
    "systems/modern20/assets/icons/delapouite/camping-tent.svg",
    "systems/modern20/assets/icons/delapouite/car-key.svg",
    "systems/modern20/assets/icons/delapouite/carnivorous-plant.svg",
    "systems/modern20/assets/icons/delapouite/cctv-camera.svg",
    "systems/modern20/assets/icons/delapouite/charging-bull.svg",
    "systems/modern20/assets/icons/delapouite/chest-armor.svg",
    "systems/modern20/assets/icons/delapouite/city-car.svg",
    "systems/modern20/assets/icons/delapouite/claws.svg",
    "systems/modern20/assets/icons/delapouite/crystal-shrine.svg",
    "systems/modern20/assets/icons/delapouite/cycling.svg",
    "systems/modern20/assets/icons/delapouite/diamond-ring.svg",
    "systems/modern20/assets/icons/delapouite/door.svg",
    "systems/modern20/assets/icons/delapouite/first-aid-kit.svg",
    "systems/modern20/assets/icons/delapouite/flail.svg",
    "systems/modern20/assets/icons/delapouite/flamethrower.svg",
    "systems/modern20/assets/icons/delapouite/flanged-mace.svg",
    "systems/modern20/assets/icons/delapouite/flashlight.svg",
    "systems/modern20/assets/icons/delapouite/floating-ghost.svg",
    "systems/modern20/assets/icons/delapouite/floating-tentacles.svg",
    "systems/modern20/assets/icons/delapouite/giant.svg",
    "systems/modern20/assets/icons/delapouite/glowing-artifact.svg",
    "systems/modern20/assets/icons/delapouite/graduate-cap.svg",
    "systems/modern20/assets/icons/delapouite/gun-stock.svg",
    "systems/modern20/assets/icons/delapouite/healing.svg",
    "systems/modern20/assets/icons/delapouite/helicopter.svg",
    "systems/modern20/assets/icons/delapouite/invisible.svg",
    "systems/modern20/assets/icons/delapouite/jeep.svg",
    "systems/modern20/assets/icons/delapouite/laptop.svg",
    "systems/modern20/assets/icons/delapouite/lockpicks.svg",
    "systems/modern20/assets/icons/delapouite/machine-gun-magazine.svg",
    "systems/modern20/assets/icons/delapouite/magic-potion.svg",
    "systems/modern20/assets/icons/delapouite/nose-side.svg",
    "systems/modern20/assets/icons/delapouite/person.svg",
    "systems/modern20/assets/icons/delapouite/perspective-dice-six-faces-random.svg",
    "systems/modern20/assets/icons/delapouite/photo-camera.svg",
    "systems/modern20/assets/icons/delapouite/police-car.svg",
    "systems/modern20/assets/icons/delapouite/rope-coil.svg",
    "systems/modern20/assets/icons/delapouite/shambling-zombie.svg",
    "systems/modern20/assets/icons/delapouite/slime.svg",
    "systems/modern20/assets/icons/delapouite/slingshot.svg",
    "systems/modern20/assets/icons/delapouite/smartphone.svg",
    "systems/modern20/assets/icons/delapouite/soccer-ball.svg",
    "systems/modern20/assets/icons/delapouite/speed-boat.svg",
    "systems/modern20/assets/icons/delapouite/swallower.svg",
    "systems/modern20/assets/icons/delapouite/toolbox.svg",
    "systems/modern20/assets/icons/delapouite/transform.svg",
    "systems/modern20/assets/icons/delapouite/truck.svg",
    "systems/modern20/assets/icons/delapouite/uzi.svg",
    "systems/modern20/assets/icons/delapouite/wallet.svg",
    "systems/modern20/assets/icons/delapouite/window-bars.svg",
    "systems/modern20/assets/icons/felbrigg/dodge.svg",
    "systems/modern20/assets/icons/john-colburn/pistol-gun.svg",
    "systems/modern20/assets/icons/lorc/armor-vest.svg",
    "systems/modern20/assets/icons/lorc/aura.svg",
    "systems/modern20/assets/icons/lorc/battle-axe.svg",
    "systems/modern20/assets/icons/lorc/battle-tank.svg",
    "systems/modern20/assets/icons/lorc/beast-eye.svg",
    "systems/modern20/assets/icons/lorc/bolas.svg",
    "systems/modern20/assets/icons/lorc/bowie-knife.svg",
    "systems/modern20/assets/icons/lorc/brain.svg",
    "systems/modern20/assets/icons/lorc/broadsword.svg",
    "systems/modern20/assets/icons/lorc/bull-horns.svg",
    "systems/modern20/assets/icons/lorc/claw-hammer.svg",
    "systems/modern20/assets/icons/lorc/cluster-bomb.svg",
    "systems/modern20/assets/icons/lorc/cog-lock.svg",
    "systems/modern20/assets/icons/lorc/crossed-chains.svg",
    "systems/modern20/assets/icons/lorc/crystal-ball.svg",
    "systems/modern20/assets/icons/lorc/crystal-wand.svg",
    "systems/modern20/assets/icons/lorc/daemon-skull.svg",
    "systems/modern20/assets/icons/lorc/dragon-breath.svg",
    "systems/modern20/assets/icons/lorc/dragon-head.svg",
    "systems/modern20/assets/icons/lorc/energy-sword.svg",
    "systems/modern20/assets/icons/lorc/fairy-wand.svg",
    "systems/modern20/assets/icons/lorc/fairy.svg",
    "systems/modern20/assets/icons/lorc/feathered-wing.svg",
    "systems/modern20/assets/icons/lorc/fire-bottle.svg",
    "systems/modern20/assets/icons/lorc/fishing-net.svg",
    "systems/modern20/assets/icons/lorc/gas-mask.svg",
    "systems/modern20/assets/icons/lorc/grab.svg",
    "systems/modern20/assets/icons/lorc/grenade.svg",
    "systems/modern20/assets/icons/lorc/halberd.svg",
    "systems/modern20/assets/icons/lorc/handcuffs.svg",
    "systems/modern20/assets/icons/lorc/horned-helm.svg",
    "systems/modern20/assets/icons/lorc/ice-spear.svg",
    "systems/modern20/assets/icons/lorc/jetpack.svg",
    "systems/modern20/assets/icons/lorc/leather-vest.svg",
    "systems/modern20/assets/icons/lorc/lightning-arc.svg",
    "systems/modern20/assets/icons/lorc/magic-palm.svg",
    "systems/modern20/assets/icons/lorc/magic-portal.svg",
    "systems/modern20/assets/icons/lorc/magic-shield.svg",
    "systems/modern20/assets/icons/lorc/magic-swirl.svg",
    "systems/modern20/assets/icons/lorc/muscle-up.svg",
    "systems/modern20/assets/icons/lorc/pierced-body.svg",
    "systems/modern20/assets/icons/lorc/poison-bottle.svg",
    "systems/modern20/assets/icons/lorc/psychic-waves.svg",
    "systems/modern20/assets/icons/lorc/punch.svg",
    "systems/modern20/assets/icons/lorc/radar-sweep.svg",
    "systems/modern20/assets/icons/lorc/rocket.svg",
    "systems/modern20/assets/icons/lorc/scroll-unfurled.svg",
    "systems/modern20/assets/icons/lorc/scythe.svg",
    "systems/modern20/assets/icons/lorc/shield-reflect.svg",
    "systems/modern20/assets/icons/lorc/sonic-shout.svg",
    "systems/modern20/assets/icons/lorc/spears.svg",
    "systems/modern20/assets/icons/lorc/spider-web.svg",
    "systems/modern20/assets/icons/lorc/spiked-tail.svg",
    "systems/modern20/assets/icons/lorc/splash.svg",
    "systems/modern20/assets/icons/lorc/spray.svg",
    "systems/modern20/assets/icons/lorc/suckered-tentacle.svg",
    "systems/modern20/assets/icons/lorc/telepathy.svg",
    "systems/modern20/assets/icons/lorc/terror.svg",
    "systems/modern20/assets/icons/lorc/third-eye.svg",
    "systems/modern20/assets/icons/lorc/thrown-knife.svg",
    "systems/modern20/assets/icons/lorc/tied-scroll.svg",
    "systems/modern20/assets/icons/lorc/trophy.svg",
    "systems/modern20/assets/icons/lorc/vintage-robot.svg",
    "systems/modern20/assets/icons/lorc/vomiting.svg",
    "systems/modern20/assets/icons/lorc/wasp-sting.svg",
    "systems/modern20/assets/icons/lorc/wolf-head.svg",
    "systems/modern20/assets/icons/lucasms/shirt.svg",
    "systems/modern20/assets/icons/quoting/field-gun.svg",
    "systems/modern20/assets/icons/sbed/acid.svg",
    "systems/modern20/assets/icons/sbed/claw.svg",
    "systems/modern20/assets/icons/sbed/fire.svg",
    "systems/modern20/assets/icons/sbed/laser-gun.svg",
    "systems/modern20/assets/icons/sbed/medical-pack.svg",
    "systems/modern20/assets/icons/sbed/rifle.svg",
    "systems/modern20/assets/icons/sbed/shotgun.svg",
    "systems/modern20/assets/icons/skoll/airplane.svg",
    "systems/modern20/assets/icons/skoll/baton.svg",
    "systems/modern20/assets/icons/skoll/brodie-helmet.svg",
    "systems/modern20/assets/icons/skoll/burning-skull.svg",
    "systems/modern20/assets/icons/skoll/fangs.svg",
    "systems/modern20/assets/icons/skoll/kevlar-vest.svg",
    "systems/modern20/assets/icons/skoll/long-legged-spider.svg",
    "systems/modern20/assets/icons/skoll/machine-gun.svg",
    "systems/modern20/assets/icons/skoll/race-car.svg",
    "systems/modern20/assets/icons/skoll/revolver.svg",
    "systems/modern20/assets/icons/zeromancer/heart-plus.svg",
    "systems/modern20/assets/media/cover-thumb.webp",
    "systems/modern20/assets/media/cover.webp",
    "systems/modern20/assets/media/warehouse.webp",
    "systems/modern20/assets/tokens/andymeneely/police-badge.svg",
    "systems/modern20/assets/tokens/delapouite/brick-wall.svg",
    "systems/modern20/assets/tokens/delapouite/bus.svg",
    "systems/modern20/assets/tokens/delapouite/carnivorous-plant.svg",
    "systems/modern20/assets/tokens/delapouite/city-car.svg",
    "systems/modern20/assets/tokens/delapouite/cycling.svg",
    "systems/modern20/assets/tokens/delapouite/door.svg",
    "systems/modern20/assets/tokens/delapouite/first-aid-kit.svg",
    "systems/modern20/assets/tokens/delapouite/floating-tentacles.svg",
    "systems/modern20/assets/tokens/delapouite/giant.svg",
    "systems/modern20/assets/tokens/delapouite/helicopter.svg",
    "systems/modern20/assets/tokens/delapouite/jeep.svg",
    "systems/modern20/assets/tokens/delapouite/person.svg",
    "systems/modern20/assets/tokens/delapouite/police-car.svg",
    "systems/modern20/assets/tokens/delapouite/rope-coil.svg",
    "systems/modern20/assets/tokens/delapouite/shambling-zombie.svg",
    "systems/modern20/assets/tokens/delapouite/slime.svg",
    "systems/modern20/assets/tokens/delapouite/speed-boat.svg",
    "systems/modern20/assets/tokens/delapouite/toolbox.svg",
    "systems/modern20/assets/tokens/delapouite/truck.svg",
    "systems/modern20/assets/tokens/delapouite/window-bars.svg",
    "systems/modern20/assets/tokens/john-colburn/pistol-gun.svg",
    "systems/modern20/assets/tokens/lorc/battle-tank.svg",
    "systems/modern20/assets/tokens/lorc/beast-eye.svg",
    "systems/modern20/assets/tokens/lorc/cog-lock.svg",
    "systems/modern20/assets/tokens/lorc/crossed-chains.svg",
    "systems/modern20/assets/tokens/lorc/daemon-skull.svg",
    "systems/modern20/assets/tokens/lorc/dragon-head.svg",
    "systems/modern20/assets/tokens/lorc/fairy.svg",
    "systems/modern20/assets/tokens/lorc/handcuffs.svg",
    "systems/modern20/assets/tokens/lorc/horned-helm.svg",
    "systems/modern20/assets/tokens/lorc/jetpack.svg",
    "systems/modern20/assets/tokens/lorc/muscle-up.svg",
    "systems/modern20/assets/tokens/lorc/vintage-robot.svg",
    "systems/modern20/assets/tokens/lorc/wolf-head.svg",
    "systems/modern20/assets/tokens/sbed/fire.svg",
    "systems/modern20/assets/tokens/sbed/medical-pack.svg",
    "systems/modern20/assets/tokens/skoll/airplane.svg",
    "systems/modern20/assets/tokens/skoll/long-legged-spider.svg",
    "systems/modern20/assets/tokens/skoll/race-car.svg"
  ]
};
